server:
  port: 9090

spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/order-platform?authSource=admin
eureka:
  client:
    enabled: true
    fetch-registry: true