server:
  port: 9091

spring:
  application:
    name: order-service
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:test
  h2:
    console:
      enabled: "true"
      path: /h2-console

# swagger documentation
springdoc:
  swagger-ui:
    enabled: true

  # product service endpoint details
products:
  api:
    host: http://localhost:9090
    endpoint: /api/v1/products/

logging:
  level:
    org:
      apache:
        hc:
          client5: DEBUG

eureka:
  client:
    enabled: true
    fetch-registry: true